imagenent_dict = {
  "tench": "丁鲷",
  "goldfish": "金鱼",
  "great white shark": "大白鲨",
  "tiger shark": "虎鲨",
  "hammerhead": "双髻鲨",
  "electric ray": "电鳐",
  "stingray": "黄貂鱼",
  "cock": "公鸡",
  "hen": "母鸡",
  "ostrich": "鸵鸟",
  "brambling": "燕雀",
  "goldfinch": "金翅雀",
  "house finch": "家朱雀",
  "junco": "灯草鹀",
  "indigo bunting": "靛蓝彩鹀",
  "robin": "知更鸟",
  "bulbul": "画眉鸟",
  "jay": "松鸦",
  "magpie": "喜鹊",
  "chickadee": "山雀",
  "water ouzel": "河乌",
  "kite": "鸢",
  "bald eagle": "白头海雕",
  "vulture": "秃鹫",
  "great grey owl": "灰林鸮",
  "European fire salamander": "欧洲火蝾螈",
  "common newt": "普通蝾螈",
  "eft": "幼年蝾螈",
  "spotted salamander": "斑点蝾螈",
  "axolotl": "美西螈",
  "bullfrog": "牛蛙",
  "tree frog": "树蛙",
  "tailed frog": "尾蛙",
  "loggerhead": "红海龟",
  "leatherback turtle": "棱皮龟",
  "mud turtle": "泥龟",
  "terrapin": "淡水龟",
  "box turtle": "箱龟",
  "banded gecko": "带纹壁虎",
  "common iguana": "美洲鬣蜥",
  "American chameleon": "美洲变色龙",
  "whiptail": "鞭尾蜥",
  "agama": "鬣蜥",
  "frilled lizard": "伞蜥",
  "alligator lizard": "鳄蜥",
  "Gila monster": "毒蜥",
  "green lizard": "绿蜥蜴",
  "African chameleon": "非洲变色龙",
  "Komodo dragon": "科莫多巨蜥",
  "African crocodile": "非洲鳄鱼",
  "American alligator": "美洲短吻鳄",
  "triceratops": "三角龙",
  "thunder snake": "雷蛇",
  "ringneck snake": "环颈蛇",
  "hognose snake": "猪鼻蛇",
  "green snake": "绿蛇",
  "king snake": "王蛇",
  "garter snake": "缠蛇",
  "water snake": "水蛇",
  "vine snake": "藤蛇",
  "night snake": "夜蛇",
  "boa constrictor": "森蚺",
  "rock python": "岩蟒",
  "Indian cobra": "印度眼镜蛇",
  "green mamba": "绿曼巴蛇",
  "sea snake": "海蛇",
  "horned viper": "角蝰",
  "diamondback": "响尾蛇",
  "sidewinder": "角蝰蛇",
  "trilobite": "三叶虫",
  "harvestman": "收获蛛",
  "scorpion": "蝎子",
  "black and gold garden spider": "黑金园蛛",
  "barn spider": "仓蛛",
  "garden spider": "园蛛",
  "black widow": "黑寡妇蜘蛛",
  "tarantula": "狼蛛",
  "wolf spider": "狼蛛",
  "tick": "蜱虫",
  "centipede": "蜈蚣",
  "black grouse": "黑琴鸡",
  "ptarmigan": "雷鸟",
  "ruffed grouse": "环颈松鸡",
  "prairie chicken": "草原松鸡",
  "peacock": "孔雀",
  "quail": "鹌鹑",
  "partridge": "鹧鸪",
  "African grey": "非洲灰鹦鹉",
  "macaw": "金刚鹦鹉",
  "sulphur-crested cockatoo": "葵花凤头鹦鹉",
  "lorikeet": "吸蜜鹦鹉",
  "coucal": "鹃鵙",
  "bee eater": "食蜂鸟",
  "hornbill": "犀鸟",
  "hummingbird": "蜂鸟",
  "jacamar": "蜂虎鸟",
  "toucan": "巨嘴鸟",
  "drake": "雄鸭",
  "red-breasted merganser": "红胸秋沙鸭",
  "goose": "鹅",
  "black swan": "黑天鹅",
  "tusker": "长牙大象",
  "echidna": "针鼹",
  "platypus": "鸭嘴兽",
  "wallaby": "小袋鼠",
  "koala": "考拉",
  "wombat": "袋熊",
  "jellyfish": "水母",
  "sea anemone": "海葵",
  "brain coral": "脑珊瑚",
  "flatworm": "扁形虫",
  "nematode": "线虫",
  "conch": "海螺",
  "snail": "蜗牛",
  "slug": "蛞蝓",
  "sea slug": "海蛞蝓",
  "chiton": "石鳖",
  "chambered nautilus": "鹦鹉螺",
  "Dungeness crab": "丹吉尼斯蟹",
  "rock crab": "岩蟹",
  "fiddler crab": "招潮蟹",
  "king crab": "帝王蟹",
  "American lobster": "美洲龙虾",
  "spiny lobster": "刺龙虾",
  "crayfish": "小龙虾",
  "hermit crab": "寄居蟹",
  "isopod": "等足类",
  "white stork": "白鹳",
  "black stork": "黑鹳",
  "spoonbill": "鹮",
  "flamingo": "火烈鸟",
  "little blue heron": "小蓝鹭",
  "American egret": "美洲白鹭",
  "bittern": "苇鳽",
  "crane": "鹤",
  "limpkin": "扁嘴鹳",
  "European gallinule": "普通秧鸡",
  "American coot": "美洲蛙鸭",
  "bustard": "鸨",
  "ruddy turnstone": "红额滨鹬",
  "red-backed sandpiper": "红背滨鹬",
  "redshank": "赤跖",
  "dowitcher": "钝嘴滨鹬",
  "oystercatcher": "蛎鹬",
  "pelican": "鹈鹕",
  "king penguin": "王企鹅",
  "albatross": "信天翁",
  "grey whale": "灰鲸",
  "killer whale": "虎鲸",
  "dugong": "海牛",
  "sea lion": "海狮",
  "Chihuahua": "吉娃娃",
  "Japanese spaniel": "日本狆",
  "Maltese dog": "马耳他犬",
  "Pekinese": "京巴犬",
  "Shih-Tzu": "西施犬",
  "Blenheim spaniel": "布伦海姆猎犬",
  "papillon": "蝶形犬",
  "toy terrier": "玩具梗",
  "Rhodesian ridgeback": "罗得西亚脊背犬",
  "Afghan hound": "阿富汗猎犬",
  "basset": "巴吉度猎犬",
  "beagle": "比格犬",
  "bloodhound": "追血猎犬",
  "bluetick": "蓝点浣熊猎犬",
  "black-and-tan coonhound": "黑黄浣熊猎犬",
  "Walker hound": "沃克猎犬",
  "English foxhound": "英国猎狐犬",
  "redbone": "红骨浣熊猎犬",
  "borzoi": "俄罗斯獒犬",
  "Irish wolfhound": "爱尔兰猎狼犬",
  "Italian greyhound": "意大利灵缇",
  "whippet": "惠比特犬",
  "Ibizan hound": "伊比沙猎犬",
  "Norwegian elkhound": "挪威麋犬",
  "otterhound": "水獭猎犬",
  "Saluki": "萨路基猎犬",
  "Scottish deerhound": "苏格兰猎鹿犬",
  "Weimaraner": "魏玛猎犬",
  "Staffordshire bullterrier": "斯塔福郡斗牛梗",
  "American Staffordshire terrier": "美国斯塔福斗牛梗",
  "Bedlington terrier": "贝德灵顿梗",
  "Border terrier": "博德梗",
  "Kerry blue terrier": "凯利蓝梗",
  "Irish terrier": "爱尔兰梗",
  "Norfolk terrier": "诺福克梗",
  "Norwich terrier": "诺里奇梗",
  "Yorkshire terrier": "约克夏梗",
  "wire-haired fox terrier": "硬毛狐狸梗",
  "Lakeland terrier": "莱克兰梗",
  "Sealyham terrier": "西利汉梗",
  "Airedale": "艾尔戴尔梗",
  "cairn": "凯恩梗",
  "Australian terrier": "澳大利亚梗",
  "Dandie Dinmont": "丹迪·丁蒙特梗",
  "Boston bull": "波士顿牛头梗",
  "miniature schnauzer": "迷你雪纳瑞",
  "giant schnauzer": "巨型雪纳瑞",
  "standard schnauzer": "标准雪纳瑞",
  "Scotch terrier": "苏格兰梗",
    "Tibetan terrier": "西藏梗",
  "silky terrier": "丝毛梗",
  "soft-coated wheaten terrier": "软毛麦色梗",
  "West Highland white terrier": "西高地白梗",
  "Lhasa": "拉萨犬",
  "flat-coated retriever": "平毛寻回犬",
  "curly-coated retriever": "卷毛寻回犬",
  "golden retriever": "金毛寻回犬",
  "Labrador retriever": "拉布拉多寻回犬",
  "Chesapeake Bay retriever": "切萨皮克湾寻回犬",
  "German short-haired pointer": "德国短毛指示犬",
  "vizsla": "维兹拉犬",
  "English setter": "英国雪达犬",
  "Irish setter": "爱尔兰雪达犬",
  "Gordon setter": "戈登雪达犬",
  "Brittany spaniel": "布列塔尼猎犬",
  "clumber": "克伦伯猎犬",
  "English springer": "英国斯宾格犬",
  "Welsh springer spaniel": "威尔士斯宾格猎犬",
  "cocker spaniel": "可卡犬",
  "Sussex spaniel": "萨塞克斯猎犬",
  "Irish water spaniel": "爱尔兰水猎犬",
  "kuvasz": "库瓦兹犬",
  "schipperke": "斯奇派克犬",
  "groenendael": "格罗安达尔犬",
  "malinois": "马里努阿犬",
  "briard": "布里亚犬",
  "kelpie": "凯尔皮犬",
  "komondor": "科蒙多犬",
  "Old English sheepdog": "英国古代牧羊犬",
  "Shetland sheepdog": "谢德兰牧羊犬",
  "collie": "柯利犬",
  "Border collie": "边境牧羊犬",
  "Bouvier des Flandres": "弗兰德斯牧牛犬",
  "Rottweiler": "罗威纳犬",
  "German shepherd": "德国牧羊犬",
  "Doberman": "杜宾犬",
  "miniature pinscher": "迷你品犬",
  "Greater Swiss Mountain dog": "大瑞士山地犬",
  "Bernese mountain dog": "伯恩山犬",
  "Appenzeller": "阿彭策尔山犬",
  "EntleBucher": "恩特勒布赫山犬",
  "boxer": "拳师犬",
  "bull mastiff": "斗牛獒犬",
  "Tibetan mastiff": "藏獒",
  "French bulldog": "法国斗牛犬",
  "Great Dane": "大丹犬",
  "Saint Bernard": "圣伯纳犬",
  "Eskimo dog": "爱斯基摩犬",
  "malamute": "阿拉斯加雪橇犬",
  "Siberian husky": "西伯利亚哈士奇",
  "dalmatian": "斑点狗",
  "affenpinscher": "猴面犬",
  "basenji": "巴仙吉犬",
  "pug": "哈巴狗",
  "Leonberg": "莱昂贝格犬",
  "Newfoundland": "纽芬兰犬",
  "Great Pyrenees": "大白熊犬",
  "Samoyed": "萨摩耶犬",
  "Pomeranian": "博美犬",
  "chow": "松狮犬",
  "keeshond": "凯斯犬",
  "Brabancon griffon": "布拉班松狮犬",
  "Pembroke": "彭布罗克柯基犬",
  "Cardigan": "卡迪根柯基犬",
  "toy poodle": "玩具贵宾犬",
  "miniature poodle": "迷你贵宾犬",
  "standard poodle": "标准贵宾犬",
  "Mexican hairless": "墨西哥无毛犬",
  "timber wolf": "灰狼",
  "white wolf": "白狼",
  "red wolf": "红狼",
  "coyote": "郊狼",
  "dingo": "澳洲野狗",
  "dhole": "豺",
  "African hunting dog": "非洲野犬",
  "hyena": "鬣狗",
  "red fox": "红狐",
  "kit fox": "小耳狐",
  "Arctic fox": "北极狐",
  "grey fox": "灰狐",
  "tabby": "虎斑猫",
  "tiger cat": "虎猫",
  "Persian cat": "波斯猫",
  "Siamese cat": "暹罗猫",
  "Egyptian cat": "埃及猫",
  "cougar": "美洲狮",
  "lynx": "猞猁",
  "leopard": "豹",
  "snow leopard": "雪豹",
  "jaguar": "美洲豹",
  "lion": "狮子",
  "tiger": "老虎",
  "cheetah": "猎豹",
  "brown bear": "棕熊",
  "American black bear": "美洲黑熊",
  "ice bear": "北极熊",
  "sloth bear": "懒熊",
  "mongoose": "猫鼬",
  "meerkat": "狐獴",
    "tiger beetle": "虎甲虫",
  "ladybug": "瓢虫",
  "ground beetle": "步行甲虫",
  "long-horned beetle": "天牛",
  "leaf beetle": "叶甲",
  "dung beetle": "屎壳郎",
  "rhinoceros beetle": "犀牛甲虫",
  "weevil": "象鼻虫",
  "fly": "苍蝇",
  "bee": "蜜蜂",
  "ant": "蚂蚁",
  "grasshopper": "蚱蜢",
  "cricket": "蟋蟀",
  "walking stick": "竹节虫",
  "cockroach": "蟑螂",
  "mantis": "螳螂",
  "cicada": "蝉",
  "leafhopper": "叶蝉",
  "lacewing": "草蛉",
  "dragonfly": "蜻蜓",
  "damselfly": "豆娘",
  "admiral": "红带蝶",
  "ringlet": "环蝶",
  "monarch": "帝王蝶",
  "cabbage butterfly": "粉蝶",
  "sulphur butterfly": "黄蝶",
  "lycaenid": "灰蝶",
  "starfish": "海星",
  "sea urchin": "海胆",
  "sea cucumber": "海参",
  "wood rabbit": "林兔",
  "hare": "野兔",
  "Angora": "安哥拉兔",
  "hamster": "仓鼠",
  "porcupine": "豪猪",
  "fox squirrel": "狐松鼠",
  "marmot": "旱獭",
  "beaver": "海狸",
  "guinea pig": "豚鼠",
  "sorrel": "栗色马",
  "zebra": "斑马",
  "hog": "猪",
  "wild boar": "野猪",
  "warthog": "疣猪",
  "hippopotamus": "河马",
  "ox": "公牛",
  "water buffalo": "水牛",
  "bison": "野牛",
  "ram": "公羊",
  "bighorn": "大角羊",
  "ibex": "羱羊",
  "hartebeest": "大角马",
  "impala": "黑斑羚",
  "gazelle": "瞪羚",
  "Arabian camel": "单峰骆驼",
  "llama": "美洲驼",
  "weasel": "黄鼠狼",
  "mink": "水貂",
  "polecat": "臭鼬鼩",
  "black-footed ferret": "黑足雪貂",
  "otter": "水獭",
  "skunk": "臭鼬",
  "badger": "獾",
  "armadillo": "犰狳",
  "three-toed sloth": "三趾树懒",
  "orangutan": "猩猩",
  "gorilla": "大猩猩",
  "chimpanzee": "黑猩猩",
  "gibbon": "长臂猿",
  "siamang": "合趾猿",
  "guenon": "长尾猴",
  "patas": "帕塔斯猴",
  "baboon": "狒狒",
  "macaque": "猕猴",
  "langur": "叶猴",
  "colobus": "疣猴",
  "proboscis monkey": "长鼻猴",
  "marmoset": "狨猴",
  "capuchin": "卷尾猴",
  "howler monkey": "吼猴",
  "titi": "蒂蒂猴",
  "spider monkey": "蜘蛛猴",
  "squirrel monkey": "松鼠猴",
  "Madagascar cat": "马岛狐猴",
  "indri": "大狐猴",
  "Indian elephant": "印度象",
  "African elephant": "非洲象",
  "lesser panda": "小熊猫",
  "giant panda": "大熊猫",
  "barracouta": "梭鱼",
  "eel": "鳗鱼",
  "coho": "银大马哈鱼",
  "rock beauty": "岩美人鱼",
  "anemone fish": "海葵鱼",
  "sturgeon": "鲟鱼",
  "gar": "雀鳝",
  "lionfish": "狮子鱼",
  "puffer": "河豚",
  "abacus": "算盘",
  "abaya": "罩袍",
    "academic gown": "学位袍",
  "accordion": "手风琴",
  "acoustic guitar": "木吉他",
  "aircraft carrier": "航空母舰",
  "airliner": "客机",
  "airship": "飞艇",
  "altar": "祭坛",
  "ambulance": "救护车",
  "amphibian": "两栖车",
  "analog clock": "指针时钟",
  "apiary": "养蜂场",
  "apron": "围裙",
  "ashcan": "垃圾桶",
  "assault rifle": "突击步枪",
  "backpack": "背包",
  "bakery": "面包店",
  "balance beam": "平衡木",
  "balloon": "气球",
  "ballpoint": "圆珠笔",
  "Band Aid": "创可贴",
  "banjo": "班卓琴",
  "bannister": "扶手",
  "barbell": "杠铃",
  "barber chair": "理发椅",
  "barbershop": "理发店",
  "barn": "谷仓",
  "barometer": "气压计",
  "barrel": "桶",
  "barrow": "手推车",
  "baseball": "棒球",
  "basketball": "篮球",
  "bassinet": "婴儿摇篮",
  "bassoon": "巴松管",
  "bathing cap": "泳帽",
  "bath towel": "浴巾",
  "bathtub": "浴缸",
  "beach wagon": "沙滩车",
  "beacon": "灯塔",
  "beaker": "烧杯",
  "bearskin": "熊皮帽",
  "beer bottle": "啤酒瓶",
  "beer glass": "啤酒杯",
  "bell cote": "钟楼",
  "bib": "围嘴",
  "bicycle-built-for-two": "双人自行车",
  "bikini": "比基尼",
  "binder": "活页夹",
  "binoculars": "望远镜",
  "birdhouse": "鸟屋",
  "boathouse": "船屋",
  "bobsled": "雪橇",
  "bolo tie": "博罗领带",
  "bonnet": "帽子",
  "bookcase": "书架",
  "bookshop": "书店",
  "bottlecap": "瓶盖",
  "bow": "弓",
  "bow tie": "领结",
  "brass": "黄铜",
  "brassiere": "胸罩",
  "breakwater": "防波堤",
  "breastplate": "胸甲",
  "broom": "扫帚",
  "bucket": "水桶",
  "buckle": "扣子",
  "bulletproof vest": "防弹背心",
  "bullet train": "子弹头列车",
  "butcher shop": "肉铺",
  "cab": "出租车",
  "caldron": "大锅",
  "candle": "蜡烛",
  "cannon": "大炮",
  "canoe": "独木舟",
  "can opener": "开罐器",
  "cardigan": "开衫毛衣",
  "car mirror": "车镜",
  "carousel": "旋转木马",
  "carpenter's kit": "木工工具箱",
  "carton": "纸箱",
  "car wheel": "车轮",
  "cash machine": "自动取款机",
  "cassette": "磁带",
  "cassette player": "卡带播放器",
  "castle": "城堡",
  "catamaran": "双体船",
  "CD player": "CD 播放器",
  "cello": "大提琴",
  "cellular telephone": "手机",
  "chain": "链条",
  "chainlink fence": "铁丝网围栏",
  "chain mail": "锁子甲",
  "chain saw": "链锯",
  "chest": "大箱子",
  "chiffonier": "五斗橱",
  "chime": "钟声",
  "china cabinet": "瓷器柜",
  "Christmas stocking": "圣诞袜",
  "church": "教堂",
  "cinema": "电影院",
  "cleaver": "菜刀",
    "cliff dwelling": "岩穴住所",
  "cloak": "斗篷",
  "clog": "木屐",
  "cocktail shaker": "调酒器",
  "coffee mug": "咖啡杯",
  "coffeepot": "咖啡壶",
  "coil": "线圈",
  "combination lock": "组合锁",
  "computer keyboard": "电脑键盘",
  "confectionery": "糖果店",
  "container ship": "集装箱船",
  "convertible": "敞篷车",
  "corkscrew": "开瓶器",
  "cornet": "短号",
  "cowboy boot": "牛仔靴",
  "cowboy hat": "牛仔帽",
  "cradle": "摇篮",
  "crash helmet": "防撞头盔",
  "crate": "板条箱",
  "crib": "婴儿床",
  "Crock Pot": "慢炖锅",
  "croquet ball": "槌球球",
  "crutch": "拐杖",
  "cuirass": "胸甲",
  "dam": "水坝",
  "desk": "书桌",
  "desktop computer": "台式电脑",
  "dial telephone": "转盘电话",
  "diaper": "尿布",
  "digital clock": "数字钟",
  "digital watch": "电子手表",
  "dining table": "餐桌",
  "dishrag": "抹布",
  "dishwasher": "洗碗机",
  "disk brake": "碟刹",
  "dock": "码头",
  "dogsled": "狗拉雪橇",
  "dome": "圆顶",
  "doormat": "门垫",
  "drilling platform": "钻井平台",
  "drum": "鼓",
  "drumstick": "鼓槌",
  "dumbbell": "哑铃",
  "Dutch oven": "荷兰锅",
  "electric fan": "电风扇",
  "electric guitar": "电吉他",
  "electric locomotive": "电力机车",
  "entertainment center": "娱乐中心柜",
  "envelope": "信封",
  "espresso maker": "意式咖啡机",
  "face powder": "粉饼",
  "feather boa": "羽毛围巾",
  "file": "锉刀",
  "fireboat": "消防船",
  "fire engine": "消防车",
  "fire screen": "炉前挡火屏",
  "flagpole": "旗杆",
  "flute": "长笛",
  "folding chair": "折叠椅",
  "football helmet": "橄榄球头盔",
  "forklift": "叉车",
  "fountain": "喷泉",
  "fountain pen": "钢笔",
  "four-poster": "四柱床",
  "freight car": "货车车厢",
  "French horn": "圆号",
  "frying pan": "煎锅",
  "fur coat": "皮草大衣",
  "garbage truck": "垃圾车",
  "gasmask": "防毒面具",
  "gas pump": "加油机",
  "goblet": "高脚酒杯",
  "go-kart": "卡丁车",
  "golf ball": "高尔夫球",
  "golfcart": "高尔夫球车",
  "gondola": "贡多拉船",
  "gong": "锣",
  "gown": "长袍",
  "grand piano": "三角钢琴",
  "greenhouse": "温室",
  "grille": "格栅",
  "grocery store": "杂货店",
  "guillotine": "断头台",
  "hair slide": "发卡",
  "hair spray": "发胶",
  "half track": "半履带车",
  "hammer": "锤子",
  "hamper": "洗衣篮",
  "hand blower": "手持吹风机",
  "hand-held computer": "掌上电脑",
  "handkerchief": "手帕",
  "hard disc": "硬盘",
  "harmonica": "口琴",
  "harp": "竖琴",
  "harvester": "收割机",
  "hatchet": "小斧头",
  "holster": "枪套",
  "home theater": "家庭影院",
  "honeycomb": "蜂巢",
    "hook": "钩子",
  "hoopskirt": "裙撑",
  "horizontal bar": "单杠",
  "horse cart": "马车",
  "hourglass": "沙漏",
  "iPod": "iPod 播放器",
  "iron": "熨斗",
  "jack-o'-lantern": "南瓜灯",
  "jean": "牛仔裤",
  "jeep": "吉普车",
  "jersey": "运动衫",
  "jigsaw puzzle": "拼图",
  "jinrikisha": "人力车",
  "joystick": "操纵杆",
  "kimono": "和服",
  "knee pad": "护膝",
  "knot": "结",
  "lab coat": "实验室外套",
  "ladle": "长柄勺",
  "lampshade": "灯罩",
  "laptop": "笔记本电脑",
  "lawn mower": "割草机",
  "lens cap": "镜头盖",
  "letter opener": "拆信刀",
  "library": "图书馆",
  "lifeboat": "救生艇",
  "lighter": "打火机",
  "limousine": "豪华轿车",
  "liner": "邮轮",
  "lipstick": "口红",
  "Loafer": "休闲鞋",
  "lotion": "乳液",
  "loudspeaker": "扬声器",
  "loupe": "放大镜",
  "lumbermill": "锯木厂",
  "magnetic compass": "磁罗盘",
  "mailbag": "邮袋",
  "mailbox": "邮箱",
  "maillot": "连体泳衣",
  "manhole cover": "井盖",
  "maraca": "响葫芦",
  "marimba": "马林巴琴",
  "mask": "面具",
  "matchstick": "火柴棍",
  "maypole": "五朔节柱",
  "maze": "迷宫",
  "measuring cup": "量杯",
  "medicine chest": "药柜",
  "megalith": "巨石",
  "microphone": "麦克风",
  "microwave": "微波炉",
  "military uniform": "军装",
  "milk can": "牛奶罐",
  "minibus": "小型巴士",
  "miniskirt": "迷你裙",
  "minivan": "小型货车",
  "missile": "导弹",
  "mitten": "连指手套",
  "mixing bowl": "搅拌碗",
  "mobile home": "活动房屋",
  "Model T": "T 型车",
  "modem": "调制解调器",
  "monastery": "修道院",
  "monitor": "显示器",
  "moped": "助力车",
  "mortar": "迫击炮 / 研钵",
  "mortarboard": "方帽（毕业帽）",
  "mosque": "清真寺",
  "mosquito net": "蚊帐",
  "motor scooter": "小型摩托车",
  "mountain bike": "山地自行车",
  "mountain tent": "山地帐篷",
  "mouse": "鼠标",
  "mousetrap": "捕鼠器",
  "moving van": "搬家货车",
  "muzzle": "口套",
  "nail": "钉子",
  "neck brace": "颈托",
  "necklace": "项链",
  "nipple": "奶嘴 / 乳头",
  "notebook": "笔记本",
  "obelisk": "方尖碑",
  "oboe": "双簧管",
  "ocarina": "陶笛",
  "odometer": "里程计",
  "oil filter": "机油滤清器",
  "organ": "管风琴",
  "oscilloscope": "示波器",
  "overskirt": "罩裙",
  "oxcart": "牛车",
  "oxygen mask": "氧气面罩",
  "packet": "小包",
  "paddle": "桨",
  "paddlewheel": "明轮",
  "padlock": "挂锁",
  "paintbrush": "画笔 / 刷子",
  "pajama": "睡衣",
  "palace": "宫殿",
  "panpipe": "排箫",
    "paper towel": "纸巾",
  "parachute": "降落伞",
  "parallel bars": "双杠",
  "park bench": "公园长椅",
  "parking meter": "停车计时器",
  "passenger car": "乘用车",
  "patio": "庭院",
  "pay-phone": "付费电话",
  "pedestal": "基座",
  "pencil box": "铅笔盒",
  "pencil sharpener": "卷笔刀",
  "perfume": "香水",
  "Petri dish": "培养皿",
  "photocopier": "复印机",
  "pick": "撬棍",
  "pickelhaube": "刺针头盔",
  "picket fence": "栅栏",
  "pickup": "皮卡车",
  "pier": "码头",
  "piggy bank": "储蓄罐",
  "pill bottle": "药瓶",
  "pillow": "枕头",
  "ping-pong ball": "乒乓球",
  "pinwheel": "风车",
  "pirate": "海盗",
  "pitcher": "投手 / 壶",
  "plane": "飞机",
  "planetarium": "天文馆",
  "plastic bag": "塑料袋",
  "plate rack": "碟架",
  "plow": "犁",
  "plunger": "皮搋子",
  "Polaroid camera": "拍立得相机",
  "pole": "杆",
  "police van": "警车",
  "poncho": "斗篷",
  "pool table": "台球桌",
  "pop bottle": "汽水瓶",
  "pot": "锅",
  "potter's wheel": "陶轮",
  "power drill": "电钻",
  "prayer rug": "祈祷毯",
  "printer": "打印机",
  "prison": "监狱",
  "projectile": "抛射物",
  "projector": "投影仪",
  "puck": "冰球",
  "punching bag": "沙袋",
  "purse": "钱包",
  "quill": "羽毛笔",
  "quilt": "被子",
  "racer": "赛车手",
  "racket": "球拍",
  "radiator": "散热器",
  "radio": "收音机",
  "radio telescope": "射电望远镜",
  "rain barrel": "雨水桶",
  "recreational vehicle": "休闲车",
  "reel": "卷轴",
  "reflex camera": "单反相机",
  "refrigerator": "冰箱",
  "remote control": "遥控器",
  "restaurant": "餐厅",
  "revolver": "左轮手枪",
  "rifle": "步枪",
  "rocking chair": "摇椅",
  "rotisserie": "转炉",
  "rubber eraser": "橡皮擦",
  "rugby ball": "橄榄球",
  "rule": "尺子",
  "running shoe": "跑鞋",
  "safe": "保险箱",
  "safety pin": "安全别针",
  "saltshaker": "盐罐",
  "sandal": "凉鞋",
  "sarong": "沙笼裙",
  "sax": "萨克斯",
  "scabbard": "刀鞘",
  "scale": "秤",
  "school bus": "校车",
  "schooner": "双桅帆船",
  "scoreboard": "记分牌",
  "screen": "屏幕",
  "screw": "螺丝",
  "screwdriver": "螺丝刀",
  "seat belt": "安全带",
  "sewing machine": "缝纫机",
  "shield": "盾牌",
  "shoe shop": "鞋店",
  "shoji": "纸拉门",
  "shopping basket": "购物篮",
  "shopping cart": "购物车",
  "shovel": "铲子",
  "shower cap": "浴帽",
  "shower curtain": "浴帘",
  "ski": "滑雪板",
  "ski mask": "滑雪面罩",
  "sleeping bag": "睡袋",
  "slide rule": "计算尺",
  "sliding door": "推拉门",
    "slot": "投币口",
  "snorkel": "呼吸管",
  "snowmobile": "雪地摩托",
  "snowplow": "除雪机",
  "soap dispenser": "肥皂分配器",
  "soccer ball": "足球",
  "sock": "袜子",
  "solar dish": "太阳能碟",
  "sombrero": "宽边草帽",
  "soup bowl": "汤碗",
  "space bar": "空格键",
  "space heater": "空间加热器",
  "space shuttle": "航天飞机",
  "spatula": "抹刀",
  "speedboat": "快艇",
  "spider web": "蜘蛛网",
  "spindle": "纺锤",
  "sports car": "跑车",
  "spotlight": "聚光灯",
  "stage": "舞台",
  "steam locomotive": "蒸汽机车",
  "steel arch bridge": "钢拱桥",
  "steel drum": "钢鼓",
  "stethoscope": "听诊器",
  "stole": "披肩",
  "stone wall": "石墙",
  "stopwatch": "秒表",
  "stove": "炉灶",
  "strainer": "滤网",
  "streetcar": "有轨电车",
  "stretcher": "担架",
  "studio couch": "沙发床",
  "stupa": "佛塔",
  "submarine": "潜水艇",
  "suit": "西装",
  "sundial": "日晷",
  "sunglass": "墨镜",
  "sunglasses": "太阳镜",
  "sunscreen": "防晒霜",
  "suspension bridge": "悬索桥",
  "swab": "棉签",
  "sweatshirt": "运动衫",
  "swimming trunks": "游泳裤",
  "swing": "秋千",
  "switch": "开关",
  "syringe": "注射器",
  "table lamp": "台灯",
  "tank": "坦克",
  "tape player": "录音机",
  "teapot": "茶壶",
  "teddy": "泰迪熊",
  "television": "电视机",
  "tennis ball": "网球",
  "thatch": "茅草",
  "theater curtain": "剧院幕布",
  "thimble": "顶针",
  "thresher": "脱粒机",
  "throne": "王座",
  "tile roof": "瓦屋顶",
  "toaster": "烤面包机",
  "tobacco shop": "烟草店",
  "toilet seat": "马桶座",
  "torch": "火炬",
  "totem pole": "图腾柱",
  "tow truck": "拖车",
  "toyshop": "玩具店",
  "tractor": "拖拉机",
  "trailer truck": "挂车卡车",
  "tray": "托盘",
  "trench coat": "风衣",
  "tricycle": "三轮车",
  "trimaran": "三体船",
  "tripod": "三脚架",
  "triumphal arch": "凯旋门",
  "trolleybus": "无轨电车",
  "trombone": "长号",
  "tub": "浴缸",
  "turnstile": "旋转闸门",
  "typewriter keyboard": "打字机键盘",
  "umbrella": "伞",
  "unicycle": "独轮车",
  "upright": "立式钢琴",
  "vacuum": "吸尘器",
  "vase": "花瓶",
  "vault": "拱顶 / 金库",
  "velvet": "天鹅绒",
  "vending machine": "自动售货机",
  "vestment": "礼服",
  "viaduct": "高架桥",
  "violin": "小提琴",
  "volleyball": "排球",
  "waffle iron": "华夫饼烤盘",
  "wall clock": "挂钟",
  "wallet": "钱包",
  "wardrobe": "衣柜",
  "warplane": "战斗机",
  "washbasin": "洗脸盆",
  "washer": "洗衣机",
  "water bottle": "水瓶",
  "water jug": "水壶",
    "water tower": "水塔",
  "whiskey jug": "威士忌壶",
  "whistle": "口哨",
  "wig": "假发",
  "window screen": "纱窗",
  "window shade": "窗帘",
  "Windsor tie": "温莎领带",
  "wine bottle": "酒瓶",
  "wing": "翼",
  "wok": "炒锅",
  "wooden spoon": "木勺",
  "wool": "羊毛",
  "worm fence": "虫形栅栏",
  "wreck": "残骸",
  "yawl": "双桅小帆船",
  "yurt": "蒙古包",
  "web site": "网站",
  "comic book": "漫画书",
  "crossword puzzle": "填字游戏",
  "street sign": "街道标志",
  "traffic light": "红绿灯",
  "book jacket": "书套",
  "menu": "菜单",
  "plate": "盘子",
  "guacamole": "鳄梨酱",
  "consomme": "清汤",
  "hot pot": "火锅",
  "trifle": "水果奶油蛋糕",
  "ice cream": "冰淇淋",
  "ice lolly": "冰棒",
  "French loaf": "法式长棍面包",
  "bagel": "百吉饼",
  "pretzel": "椒盐卷饼",
  "cheeseburger": "芝士汉堡",
  "hotdog": "热狗",
  "mashed potato": "土豆泥",
  "head cabbage": "卷心菜",
  "broccoli": "西兰花",
  "cauliflower": "花椰菜",
  "zucchini": "西葫芦",
  "spaghetti squash": "意大利面瓜",
  "acorn squash": "橡果南瓜",
  "butternut squash": "奶油南瓜",
  "cucumber": "黄瓜",
  "artichoke": "洋蓟",
  "bell pepper": "甜椒",
  "cardoon": "蓟",
  "mushroom": "蘑菇",
  "Granny Smith": "格兰尼史密斯苹果",
  "strawberry": "草莓",
  "orange": "橙子",
  "lemon": "柠檬",
  "fig": "无花果",
  "pineapple": "菠萝",
  "banana": "香蕉",
  "jackfruit": "菠萝蜜",
  "custard apple": "释迦",
  "pomegranate": "石榴",
  "hay": "干草",
  "carbonara": "卡邦尼意面",
  "chocolate sauce": "巧克力酱",
  "dough": "面团",
  "meat loaf": "肉饼",
  "pizza": "披萨",
  "potpie": "肉馅饼",
  "burrito": "墨西哥卷饼",
  "red wine": "红酒",
  "espresso": "浓缩咖啡",
  "cup": "杯子",
  "eggnog": "蛋奶酒",
  "alp": "高山",
  "bubble": "气泡",
  "cliff": "悬崖",
  "coral reef": "珊瑚礁",
  "geyser": "间歇泉",
  "lakeside": "湖边",
  "promontory": "海角",
  "sandbar": "沙洲",
  "seashore": "海滨",
  "valley": "山谷",
  "volcano": "火山",
  "ballplayer": "球员",
  "groom": "新郎",
  "scuba diver": "水肺潜水员",
  "rapeseed": "油菜",
  "daisy": "雏菊",
  "yellow lady's slipper": "黄花杓兰",
  "corn": "玉米",
  "acorn": "橡子",
  "hip": "玫瑰果",
  "buckeye": "眼子果",
  "coral fungus": "珊瑚菌",
  "agaric": "伞菌",
  "gyromitra": "毛头伞菌",
  "stinkhorn": "臭角菌",
  "earthstar": "地星菌",
  "hen-of-the-woods": "羊肚菌",
  "bolete": "牛肝菌",
  "ear": "谷穗",
  "toilet tissue": "卫生纸"
}
